[package]
name = "wordle_api"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
rand = "0.8.5"
serde = { version = "1.0.210", features = ["derive"] }
tokio = { version = "1.40.0", features = ["tokio-macros", "full", "time"] }
warp = "0.3.7"
